### ISSUE TITLE
upload ke debian

### ISSUE THREAD

**Issue by guspur** [ubunteroz/ignsdk#1]
saya dan kawan-kawan blankon  berencana merawat paket ign-sdk di debian.org mohon bimbingan. saat ini rekan-rekan blankon telah bergabung di https://alioth.debian.org/projects/blankon/

**Comment by ubunteroz** [comment]
Terima kasih sebelumnya atas kesediaan rekan-rekan untuk jadi _maintainer_ paket IGNSDK di Debian. Repo ini memang saya tujukan khusus bagi paket IGNSDK untuk Debian. Versi yang saya rasa "_stable_" ada di bagian **Releases**.

FYI, saya tidak paham betul detail _guidelines_ pemaketan untuk diunggah ke repo utama Debian. Jadi, mungkin perlu banyak perubahan di bagian _control files_-nya. Beberapa aspek seperti _semantic versioning_ dan _hardening_ juga belum saya aplikasikan.

Saya jarang buka GitHub, jadi silakan hubungi via email saja. Terima kasih.
